#!/usr/bin/env zsh

# Path
export PATH="$PATH:/home/undeadamien/.local/bin"

# General
setopt rmstarsilent

# Neovim config
export EDITOR="nvim"

# Fzf config
source <(fzf --zsh)
export FZF_DEFAULT_OPTS="
    --style full \
    --reverse \
    --cycle \
    --ansi \
    --smart-case \
    --scheme=path \
    --border \
    --height 40% --min-height 20 \
    --preview 'sh -c \"jp2a --fill --colors --width=\$FZF_PREVIEW_COLUMNS {} 2>/dev/null || bat --color=always --style=plain {} 2>/dev/null || ls -l {}\"' \
    --preview-window=right:50%
"
#todo: configure fzf-tab: https://github.com/Aloxaf/fzf-tab?tab=readme-ov-file#configure

# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt hist_ignore_dups
setopt hist_reduce_blanks

# Antidote
[ -f ~/.antidote/antidote.zsh ] || git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
source ~/.antidote/antidote.zsh
antidote load

# Completion
autoload -Uz compinit && compinit
setopt globdots

# Prompt
autoload -Uz promptinit && promptinit
setopt prompt_subst
function update_prompt {
    PROMPT=$''
    PROMPT+=$'%B%n%b'
    PROMPT+=$':'
    PROMPT+=$'%~'
    PROMPT+=$'%B$%b'
    PROMPT+=$' '
}
update_prompt

# Cli
bindkey -v
autoload -U edit-command-line && zle -N edit-command-line

# Nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# cd with fzf
function fd() {
    local selected="$(fzf --walker=file,dir,hidden --walker-skip=.cache,.local,node_modules,.git)"
    if [ -z "${selected}" ]; then return; fi
    selected="$(realpath "$selected")"
    target_dir="$selected"
    if [ -f "${selected}" ]; then target_dir="$(dirname "$selected")"; fi
    cd "$target_dir"
}

# Hooks
autoload -Uz add-zsh-hook
function auto_ls() {
    ls
}
add-zsh-hook chpwd auto_ls
