#!/usr/bin/env zsh

# Stow
export PATH="$HOME/.local/bin:$PATH"

# Neovim config
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
export PATH="$PATH:$HOME/.local/share/nvim/bin" # for the school
export EDITOR="nvim"

# Fzf config
export FZF_DEFAULT_OPTS="\
	--reverse \
	--cycle \
	--smart-case \
	--scheme=path \
	--border \
	--preview 'sh -c \"jp2a --fill --colors --width=\$FZF_PREVIEW_COLUMNS {} 2>/dev/null || bat --color=always --style=plain {} 2>/dev/null || ls -l {}\"' \
	--preview-window=right:40% "

# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt hist_ignore_dups
setopt hist_reduce_blanks

# Antidote
[ -f ~/.antidote/antidote.zsh ] || git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
source ~/.antidote/antidote.zsh
antidote load

# Completion
autoload -Uz compinit && compinit
setopt globdots

# Prompt
autoload -Uz promptinit && promptinit
setopt prompt_subst
function update_prompt {
	PROMPT=$''
	PROMPT+=$'%B%n%b'
	PROMPT+=$':'
	PROMPT+=$'%~'
	PROMPT+=$'%B$%b'
	PROMPT+=$' '
}
update_prompt

# Cli
bindkey -v
autoload -U edit-command-line && zle -N edit-command-line

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

function fd() {
	local selected="$(fzf --walker=file,dir,hidden --walker-skip=.cache,.local,node_modules,.git)"
	if [ -z "${selected}" ]; then return; fi
	selected="$(realpath "$selected")"
	target_dir="$selected"
	if [ -f "${selected}" ]; then target_dir="$(dirname "$selected")"; fi
	cd "$target_dir"
	if [ -f "${selected}" ]; then "$EDITOR" "$selected"; fi
}
