local builtin = require("telescope.builtin")

vim.keymap.set("n", "<leader>fa", function()
	builtin.find_files({ hidden = true, no_ignore = true, follow = true })
end)
vim.keymap.set("n", "<leader>fc", function()
	builtin.current_buffer_fuzzy_find({ skip_empty_lines = true })
end)
vim.keymap.set("n", "<leader>fd", builtin.diagnostics, {})
vim.keymap.set("n", "<leader>ff", function()
	builtin.find_files({ follow = true })
end)
vim.keymap.set("n", "<leader>fg", builtin.live_grep, {})
vim.keymap.set("n", "<leader>fh", builtin.help_tags, {})
vim.keymap.set("n", "<leader>fm", builtin.marks, {})
vim.keymap.set("n", "<leader>ft", builtin.treesitter, {})
vim.keymap.set("n", "<leader>gb", builtin.git_branches, {})
vim.keymap.set("n", "<leader>gs", builtin.git_status, {})
vim.keymap.set("n", "<leader>r", builtin.resume, {})
