#!/usr/bin/env zsh

# Neovim Config
export PATH="$PATH:/opt/nvim-linux64/bin"
export EDITOR="nvim"

# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# Plugins with antidote
if [ ! -f ~/.antidote/antidote.zsh ]; then
	git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
fi
source ~/.antidote/antidote.zsh
autoload -Uz compinit && compinit
antidote load

# Terminal Prompt
# Info: man zshmisc
autoload -Uz promptinit && promptinit
setopt prompt_subst
function update_prompt {
	PROMPT=$'%n:%~$ '
}
update_prompt

# Set Binds
bindkey -v
