#!/usr/bin/env zsh

# Neovim Config
export PATH="$PATH:/opt/nvim-linux64/bin"
export PATH="$PATH:$HOME/nvim/bin" # for the school
export EDITOR="nvim"

# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# Plugins with antidote
if [ ! -f ~/.antidote/antidote.zsh ]; then
	git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
fi
source ~/.antidote/antidote.zsh
autoload -Uz compinit && compinit
antidote load

# Terminal Prompt
# Info: man zshmisc
autoload -Uz promptinit && promptinit
setopt prompt_subst
function update_prompt {
	PROMPT=$''
	PROMPT+=$'%B%n%b'
	PROMPT+=$':'
	PROMPT+=$'%F{white}%{\e[3m%}%~%{\e[0m%}%f'
	PROMPT+=$'%B$%b'
	PROMPT+=$' '
}
update_prompt

# Set Binds
bindkey -v

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
