#!/usr/bin/env zsh

setopt globdots # Allow hidden element in completion

# Neovim Config
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
export PATH="$PATH:$HOME/nvim/bin" # for the school
export EDITOR="nvim"

# History
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# Plugins with antidote
[ -f ~/.antidote/antidote.zsh ] || git clone --depth=1 https://github.com/mattmc3/antidote.git ~/.antidote
source ~/.antidote/antidote.zsh
autoload -Uz compinit && compinit
antidote load

# Terminal Prompt
autoload -Uz promptinit && promptinit
setopt prompt_subst
function update_prompt {
	PROMPT=$''
	PROMPT+=$'%B%n%b'
	PROMPT+=$':'
	PROMPT+=$'%~'
	PROMPT+=$'%B$%b'
	PROMPT+=$' '
}
update_prompt

# Set Binds
bindkey -v
autoload -U edit-command-line && zle -N edit-command-line

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

function fzd() {
	local dir=${1:-"."}
	local selected="$(find "$dir" -type d 2>/dev/null | fzf)"
	[ -n "$selected" ] && cd "$selected"
}
