services:
  user:
    - mpd.service
    - syncthing.service
    - xppentablet.service
    - hyprpolkitagent.service
    - ydotool.service
    - wayland-pipewire-idle-inhibit.service
  system:
    - bluetooth.service
